homeassistant:
  name: Home
  customize: !include customize.yaml
  elevation: 94
  unit_system: imperial
  latitude: !secret home_lat
  longitude: !secret home_long
  time_zone: America/Chicago
  
config:

map:

recorder:
  purge_interval: 1
  purge_keep_days: 7

sun:

zone:
  name: Work
  latitude: !secret work_lat
  longitude: !secret work_long
  radius: 500 
  icon: mdi:worker

zone 2:
  name: Bethany's House
  latitude: !secret bethany_lat
  longitude: !secret bethany_long
  radius: 500
  icon: mdi:heart

zone 3:
  name: Dan and Marilyn's
  latitude: !secret dan_lat
  longitude: !secret dan_long
  radius: 500
  icon: mdi:home-variant

zone 4:
  name: Wayne and Lisa's
  latitude: !secret wayne_lat
  longitude: !secret wanye_long
  radius: 500
  icon: mdi:home-variant

zone 5:
  name: Michael and Mandy's
  latitude: !secret michael_lat
  longitude: !secret michael_long
  radius: 500
  icon: mdi:home-variant

zone 6:
  name: Kimberly and Travis'
  latitude: !secret travis_lat
  longitude: !secret travis_long
  radius: 500
  icon: mdi:home-variant

proximity:
  home:
    devices:
      - device_tracker.owntracks_android 
      - device_tracker.bethany_iphone
    tolerance: 50
    unit_of_measurement: mi

apcupsd:
  host: 10.0.1.6
  port: 3551

#media_player:
#  platform: plex

# Checks for available updates
updater:
  include_used_components: true

# Enables the frontend
frontend:
  javascript_version: latest
  themes:
    darkred:
      # Main colors that can be changed
      dark-primary-color: "#c66900"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      light-primary-color: "#e06c6c"
      paper-card-background-color: "#1d1d1d"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      primary-background-color: "#303030"
      primary-color: "#d32f2f"
      primary-text-color: "#cfcfcf"
      secondary-background-color: "#131313"
      sidebar-text_-_background: "#62717b" 
      # Colors based on variables, see above
      paper-card-header-color: "var(--paper-item-icon-color)" 
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-listbox-color: "var(--primary-text-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
      secondary-text-color: "var(--primary-color)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"

# Enables support for tracking state changes over time.
history:
  exclude:
    entities:
      - sensor.backdoor
      - sensor.frontdoor
      - sensor.last_boot
      - sensor.moon_phase
      - sensor.bed_toggle_switch
      - sensor.ac_history
      - sensor.dark_sky_icon
      - sensor.dark_sky_summary
    domains:
      - automation
      - camera
      - group
      - notify
      - scene
      - script
      - shell_command
      - sun
      - zone
      - zwave

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.average_load_1m

# Discover some devices automatically
#discovery:

http:
  api_password: !secret api_password
  server_port: 8123
  #Using nginx proxy to serve https over ipv4/ipv6

#Local MQTT Only (local devices publish here, and I subscribe over ssl via bridged remote MQTT)
mqtt:
  broker: 127.0.0.1
  port: 1883
  keepalive: 60
  username: !secret owntracks_user
  password: !secret owntracks_password

device_tracker:
  - platform: owntracks
  - platform: bluetooth_tracker
    interval_seconds: 30
    track_new_devices: False
  - platform: nmap_tracker
    hosts: 10.0.1.13/32
    home_interval: 10
  - platform: tile
    username: !secret tile_user
    password: !secret tile_password

climate:
  platform: radiotherm
  host:
    - 10.0.1.29
  hold_temp: True

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: notify_push_android
  - platform: pushover
    name: home assistant
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

influxdb:
  host: localhost
  username: !secret influx_user
  password: !secret influx_password

ifttt:
  key: !secret ifttt_key

light:
  - platform: limitlessled
    bridges:
      - host: 10.0.1.47
        version: 5
        port: 8899
        groups:
        - number: 1
          type: rgbw
          name: andrew_bedroom
          fade: on
        - number: 2
          type: rgbw
          name: andrew_monitor_backlight
          fade: on

zwave:
  usb_path: /dev/zwave

wemo:

emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - script
    - fan

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

panel_iframe:
  plane_tracking:
    title: 'Plane Tracking'
    icon: mdi:airplane
    url: !secret plane
  ups:
    title: 'UPS Status'
    icon: mdi:car-battery
    url: !secret ups
  grafana:
    title: 'Grafana'
    icon: mdi:chart-areaspline
    url: !secret grafana

alexa:

usps:
  driver: chrome
  username: !secret usps_username
  password: !secret usps_key

intent_script: !include intent_script.yaml
camera: !include camera.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
automation: !include automation.yaml
group: !include group.yaml
scene: !include scene.yaml
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
shell_command: !include shell_command.yaml
