- platform: arlo

- platform: fedex
  username: !secret fedex_username
  password: !secret fedex_password

- platform: ups
  username: !secret ups_username
  password: !secret ups_password

#Tell me when to change a thing
- platform: date_reminder
  name: AC Filter Change
  #Date last done/changed
  # dd-mm-yyyy
  start_date: "03-06-2018 20:00"
  #When to remind me in days
  days_in_future: 90

#Tell me when to change a thing
- platform: date_reminder
  name: Brita Filter Change
  #Date last done/changed
  # dd-mm-yyyy
  start_date: "26-06-2018 17:00"
  #When to remind me in days
  days_in_future: 90

- platform: cert_expiry
  host: !secret domain

#- platform: miflora
#  mac: "c4:7c:8d:63:34:c8"
#  name: Jade Clippings
#  force_update: false
#  median: 3
#  monitored_conditions:
#    - moisture
#    - light
#    - temperature
#    - conductivity
#    - battery

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - temperature
    - apparent_temperature
    - humidity
    - pressure
    - precip_probability
    - precip_intensity
    - wind_speed
    - wind_bearing
    - icon

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: network_in
      arg: eno1
    - type: network_out
      arg: eno1
    - type: last_boot
    - type: processor_use
    - type: load_1m

- platform: apcupsd
  resources:
    - loadpct
    - bcharge
    - timeleft

- platform: mqtt
  state_topic: 'office-toggle/state'
  name: 'Office Toggle Switch'
  qos: 1
  value_template: "{{ value_json.enabled }}"

- platform: mqtt
  state_topic: "owntracks/owntracks/Android"
  name: "Andrew Phone Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "moon"
  name: "Moon Phase"
  value_template: "{{ value_json.phase }}"

- platform: mqtt
  state_topic: "sensor/mom_and_dad_gate"
  name: "Mom and Dad Gate"

####################
# BEGIN SONOFF POW #
####################
- platform: mqtt
  name: Sonoff Pow Yesterday Energy
  unit_of_measurement: "kWh"
  state_topic: "tele/sonoff_pow_1/ENERGY"
  value_template: "{{ value_json.Yesterday }}"

- platform: mqtt
  name: Sonoff Pow Today Energy
  unit_of_measurement: "kWh"
  state_topic: "tele/sonoff_pow_1/ENERGY"
  value_template: "{{ value_json.Today }}"

- platform: mqtt
  name: Sonoff Pow Current
  unit_of_measurement: "Amps"
  state_topic: "tele/sonoff_pow_1/ENERGY"
  value_template: "{{ value_json.Current }}"

- platform: mqtt
  name: Sonoff Pow Power
  unit_of_measurement: "Watts"
  state_topic: "tele/sonoff_pow_1/ENERGY"
  value_template: "{{ value_json.Power }}"

- platform: template
  sensors:
    sonoff_pow_today_cost:
      friendly_name: Sonoff Pow Today Cost
      unit_of_measurement: "$"
      value_template: >-
        {{ states.sensor.sonoff_pow_today_energy.state  | multiply(0.1123) | round(2) }} 
    sonoff_pow_yesterday_cost:
      friendly_name: Sonoff Pow Yesterday Cost
      unit_of_measurement: "$"
      value_template: >-
        {{ states.sensor.sonoff_pow_yesterday_energy.state  | multiply(0.1123) | round(2) }}



###################
# MQTT THERMOSTAT #
###################

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat Temperature"
  unit_of_measurement: "°F"
  value_template: "{{ value_json.temp }}"

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat Operating Mode"
  value_template: "{% if value_json.tmode == 0 %}Off{% elif value_json.tmode == 1 %}Heat{% elif value_json.tmode == 2 %}Cool{% elif value_json.tmode == 3 %}Auto{% endif %}"

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat Fan Mode" 
  value_template: "{% if value_json.fmode == 0 %}Auto{% elif value_json.fmode == 1 %}Auto/Circulate{% elif value_json.fmode == 2 %}On{% endif %}"

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat State" 
  value_template: "{% if value_json.tstate == 0 %}Idle{% elif value_json.tstate == 1 %}Heating{% elif value_json.tstate == 2 %}Cooling{% endif %}"

- platform: mqtt
  state_topic: "thermostat"
  unit_of_measurement: "°F"
  name: "Thermostat Setpoint"
  value_template: "{{ value_json.setpoint }}"

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat Fan Status"
  value_template: "{% if value_json.fstate == 0 %}Off{% elif value_json.fstate == 1 %}On{% endif %}"

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat Hold"
  value_template: "{% if value_json.hold == 1 %}True{% else %}False{% endif %}"

- platform: history_stats
  name: ac_runtime_today
  entity_id: sensor.thermostat_state
  state: 'Cooling'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: ac_runtime_today_heat
  entity_id: sensor.thermostat_state
  state: 'Heating'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: ac_runtime_yesterday
  entity_id: sensor.thermostat_state
  state: 'Cooling'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24

- platform: history_stats
  name: ac_runtime_yesterday_heat
  entity_id: sensor.thermostat_state
  state: 'Heating'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24

#######
# DHT #
#######

- platform: mqtt
  state_topic: "sensor/dht_mini_1"
  unit_of_measurement: "°F"
  name: "Master Bedroom Temperature"
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_1"
  name: "Master Bedroom Humidity"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_1"
  name: "Master Bedroom Heat Index"
  unit_of_measurement: "°F"
  value_template: "{{ value_json.heat_index }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_2"
  name: "Rack Exhaust Temperature"
  unit_of_measurement: "°F"
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_2"
  name: "Rack Exhaust Humidity"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_2"
  name: "Rack Exhaust Heat Index"
  unit_of_measurement: "°F"
  value_template: "{{ value_json.heat_index }}"


#####################
# PHYSICAL SECURITY #
#####################

- platform: mqtt
  state_topic: "sensor/backdoor"
  name: "Backdoor"
  value_template: "{{ value_json.opened }}"

- platform: mqtt
  state_topic: "sensor/frontdoor"
  name: "Frontdoor"
  value_template: "{{ value_json.opened }}"


#############
# TEMPLATES #
#############

- platform: template
  sensors:
    front_door_status:
      value_template: >-
        {%- if is_state("sensor.frontdoor", "true") %}
          Open
        {%- else %}
          Closed
        {%- endif %}
      friendly_name: 'Front Door Status'

- platform: template
  sensors:
    back_door_status:
      value_template: >-
        {%- if is_state("sensor.backdoor", "true") %}
          Open
        {%- else %}
          Closed
        {%- endif %}
      friendly_name: 'Back Door Status'

#- platform: template
#  sensors:
#    front_door:
#      value_template: >-
#        {%- if is_state("sensor.linear_unknown_type2001_id0102_alarm_level_2_1", "255") -%}
#          open
#        {%- else -%}
#          closed
#        {%- endif %}

- platform: template
  sensors:
    packages_in_transit:
      friendly_name: "Packages in Transit"
      value_template: >
        {% macro in_transit(sensor) %}
          {{sensor.state|int - delivered(sensor)|int}}
        {% endmacro %}
        {% macro delivered(sensor) %}
          {% if 'delivered' in sensor.attributes %}
            {{sensor.attributes.delivered}}
          {% else %}
             0
          {% endif %}
        {% endmacro %}
        {{in_transit(states.sensor.usps_packages)|int + in_transit(states.sensor.ups)|int + in_transit(states.sensor.fedex)|int}}
    deliveries_today:
      friendly_name: "Packages Delivered Today"
      value_template: >
        {% macro delivered(sensor) %}
          {% if 'delivered' in sensor.attributes %}
            {{sensor.attributes.delivered}}
          {% else %}
             0
          {% endif %}
        {% endmacro %}
        {{delivered(states.sensor.usps_packages)|int + delivered(states.sensor.ups)|int + delivered(states.sensor.fedex)|int}}

- platform: mqtt
  state_topic: "sensor/dht_mini_temp"
  unit_of_measurement: "°F"
  name: "Outdoor Plant Temperature"
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_temp"
  name: "Outdoor Plant Humidity"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_temp"
  name: "Outdoor Plant Heat Index"
  unit_of_measurement: "°F"
  value_template: "{{ value_json.heat_index }}"
