- platform: orvibo
  discovery: false
  switches:
  -  host: 10.0.1.11
     name: living_room_lamp
  -  host: 10.0.1.21
     name: andrew_sound_machine

#- platform : mqtt
#  name: "Stupid Red Light"
#  state_topic: "light/red_light"
#  command_topic: "light/red_light"
#  payload_on: "ON"
#  payload_off: "OFF"
#  retain: true

- platform : mqtt
  name: "Rack Exhaust Fan"
  state_topic: "cmnd/sonoff_rack_fan/POWER"
  command_topic: "cmnd/sonoff_rack_fan/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: true

- platform : mqtt
  name: "Sketchy Sonoff Green Cable"
  state_topic: "cmnd/sonoff_plant_light/POWER"
  command_topic: "cmnd/sonoff_plant_light/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: true

- platform : mqtt
  name: "Decorative LED"
  state_topic: "stat/sonoff_pow_1/POWER"
  command_topic: "cmnd/sonoff_pow_1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: true

- platform: wake_on_lan
  name: "NAS" 
  mac_address: "e8:fc:af:e6:22:26"
  host: 10.0.1.20
  turn_off:
      service: shell_command.nas_poweroff

- platform: command_line
  switches:
    tv:
      command_on: echo 38000,1,1,172,172,22,64,22,64,22,64,22,21,22,21,22,21,22,21,22,21,22,64,22,64,22,64,22,21,22,21,22,21,22,21,22,21,22,64,22,21,22,21,22,64,22,64,22,21,22,21,22,64,22,21,22,64,22,64,22,21,22,21,22,64,22,64,22,21,22,1820 | nc 10.0.1.115 4998
      command_off: echo 38000,1,1,173,173,21,65,21,65,21,65,21,21,21,21,21,21,21,21,21,21,21,65,21,65,21,65,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,65,21,65,21,21,21,21,21,65,21,65,21,65,21,65,21,21,21,21,21,65,21,65,21,21,21,1832 | nc 10.0.1.115 4998
