- platform: orvibo
  discovery: false
  switches:
  -  host: 10.0.1.11
     name: living_room_lamp
  -  host: 10.0.1.21
     name: master_bedroom_sound_machine

- platform: broadlink
  host: 10.0.1.30
  mac: b4:43:0d:ae:61:36
  type:  sp2
  friendly_name: 'Kitchen Plant Light Incandescent'

#- platform : mqtt
#  name: "Stupid Red Light"
#  state_topic: "light/red_light"
#  command_topic: "light/red_light"
#  payload_on: "ON"
#  payload_off: "OFF"
#  retain: true

- platform : mqtt
  name: "Rack Exhaust Fan"
  state_topic: "cmnd/sonoff_rack_fan/POWER"
  command_topic: "cmnd/sonoff_rack_fan/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: true

- platform : mqtt
  name: "Sketchy Sonoff Green Cable"
  state_topic: "cmnd/sonoff_plant_light/POWER"
  command_topic: "cmnd/sonoff_plant_light/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: true

- platform : mqtt
  name: "Decorative LED"
  state_topic: "stat/sonoff_pow_1/POWER"
  command_topic: "cmnd/sonoff_pow_1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: true

- platform: wake_on_lan
  name: "NAS" 
  mac_address: "e8:fc:af:e6:22:26"
  host: 10.0.1.20
  turn_off:
      service: shell_command.nas_poweroff

- platform: command_line
  switches:
    tv:
      command_on: echo 38000,1,1,172,172,22,64,22,64,22,64,22,21,22,21,22,21,22,21,22,21,22,64,22,64,22,64,22,21,22,21,22,21,22,21,22,21,22,64,22,21,22,21,22,64,22,64,22,21,22,21,22,64,22,21,22,64,22,64,22,21,22,21,22,64,22,64,22,21,22,1820 | nc 10.0.1.8 4998
      command_off: echo 38000,1,1,173,173,21,65,21,65,21,65,21,21,21,21,21,21,21,21,21,21,21,65,21,65,21,65,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,65,21,65,21,21,21,21,21,65,21,65,21,65,21,65,21,21,21,21,21,65,21,65,21,21,21,1832 | nc 10.0.1.8 4998

- platform: tuya
  name: Andrew's Lamp
  host: 10.0.1.35
  local_key: 519410efeeacd057
  device_id: 263421505ccf7fbc2ef1
  id: 1

- platform: tuya
  name: Bethany's Lamp
  host: 10.0.1.38
  local_key: 519410efeeacd057
  device_id: 263421505ccf7fbc2ef1
  id: 2
